<?php

declare(strict_types=1);

namespace justinholtweb\sanka\services;

use Craft;
use craft\base\Component;
use craft\db\Query;
use craft\helpers\Db;
use craft\helpers\UrlHelper;
use DateTime;
use justinholtweb\sanka\models\CrawlerAgent;
use justinholtweb\sanka\models\Settings;
use justinholtweb\sanka\Plugin;
use justinholtweb\sanka\records\CrawlRecord;

/**
 * Who is allowed to read the site, and who actually did.
 *
 * The visit log is the part with no equivalent anywhere else. “Is ChatGPT reading my site, and what
 * is it reading?” is currently answered by grepping access logs, if it is answered at all, and it
 * is the question everyone asks first. Matching costs one precompiled regex against the user agent
 * and nothing at all on a miss, which is what makes it affordable to run on every request.
 *
 * Rows say “something claimed to be this agent”, not “this agent”. Spoofing a user agent is one
 * line of curl, and a log that quietly conflates the two would be worse than no log. Verification
 * is forward-confirmed reverse DNS, run later in batches by a console command, because two DNS
 * round trips cannot happen on the request being logged.
 */
class Crawlers extends Component
{
    /**
     * The registrable domains each vendor's crawlers resolve under.
     *
     * A vendor missing from this map cannot be verified either way, and its rows keep `verified` as
     * null rather than being marked false — “unknown” and “forged” are different claims.
     *
     * @var array<string, list<string>>
     */
    private const VENDOR_DOMAINS = [
        'OpenAI' => ['openai.com'],
        'Anthropic' => ['anthropic.com'],
        'Perplexity' => ['perplexity.ai', 'perplexity.com'],
        'Google' => ['google.com', 'googlebot.com', 'googleusercontent.com'],
        'Apple' => ['apple.com'],
        'Amazon' => ['amazonbot.amazon', 'amazon.com', 'crawl.amazonbot.amazon'],
        'ByteDance' => ['bytedance.com', 'bytedance.net', 'bytedance.sg'],
        'Meta' => ['facebook.com', 'fbsv.net', 'tfbnw.net'],
        'Common Crawl' => ['commoncrawl.org'],
        'DuckDuckGo' => ['duckduckgo.com'],
        'You.com' => ['you.com'],
    ];

    /** What `cpTrigger` is when nobody has changed it. */
    private const DEFAULT_CP_TRIGGER = 'admin';

    private ?string $signatureRegex = null;

    // ----------------------------------------------------------------- policy

    /**
     * Which parts {@see self::robotsTxt()} will emit, all on unless switched off.
     *
     * Named so a template can leave out whatever its existing robots.txt already says. A site
     * running SEOmatic has sitemaps, an allow-all group and a control panel line of its own, and
     * pasting Sanka's whole file underneath produces a robots.txt that contradicts itself —
     * `craft.sanka.robots({ sitemaps: false, default: false, cp: false })` gives it just the AI
     * crawler policy, which is the only part SEOmatic has no answer for.
     *
     * @var array<string, bool>
     */
    public const ROBOTS_SECTIONS = [
        'header' => true,
        'crawlers' => true,
        'default' => true,
        'cp' => true,
        'extra' => true,
        'sitemaps' => true,
        'llms' => true,
    ];

    /**
     * The robots.txt Sanka would serve.
     *
     * Blocked agents first, each with its own group, then a permissive default, then the sitemaps.
     * Agents are emitted one group per agent rather than as a shared list because robots.txt has no
     * precedence rules worth relying on and every crawler parses grouped records differently.
     *
     * @param array<string, bool> $sections which parts to emit; see {@see self::ROBOTS_SECTIONS}
     */
    public function robotsTxt(?int $siteId = null, array $sections = []): string
    {
        $settings = Plugin::getInstance()->getSettings();
        $want = static fn(string $section): bool => (bool)($sections[$section] ?? self::ROBOTS_SECTIONS[$section]);

        $lines = [];

        if ($want('header')) {
            $lines[] = '# Generated by Sanka. Edit the crawler policy in the control panel, not here.';
        }

        if ($want('crawlers')) {
            foreach ($settings->blockedAgents() as $token) {
                $agent = CrawlerAgent::find($token);
                $lines[] = '';

                if ($agent !== null) {
                    $lines[] = "# {$agent->vendor} — {$agent->purposeLabel()}";
                }

                $lines[] = "User-agent: {$token}";
                $lines[] = 'Disallow: /';
            }
        }

        if ($want('default')) {
            $lines[] = '';
            $lines[] = 'User-agent: *';
            $lines[] = 'Allow: /';
        }

        if ($want('cp')) {
            foreach ($this->cpDisallows() as $path) {
                $lines[] = "Disallow: {$path}";
            }
        }

        $extra = trim($settings->robotsExtra);

        if ($want('extra') && $extra !== '') {
            $lines[] = '';
            $lines[] = $extra;
        }

        $sitemaps = $want('sitemaps')
            ? Plugin::getInstance()->engines->getSitemap()->sitemapUrls()
            : [];

        if ($sitemaps !== []) {
            $lines[] = '';

            foreach ($sitemaps as $sitemap) {
                $lines[] = "Sitemap: {$sitemap}";
            }
        }

        if ($want('llms') && $settings->llmsEnabled) {
            $lines[] = '';
            $lines[] = '# ' . Craft::t('sanka', 'A map written for language models.');
            $lines[] = '# ' . UrlHelper::siteUrl('llms.txt', null, null, $siteId);
        }

        // Leaving out the first section otherwise opens the file with a blank line, and a fragment
        // pasted into somebody else's template should start where they put it.
        while (($lines[0] ?? null) === '') {
            array_shift($lines);
        }

        return $lines === [] ? '' : implode("\n", $lines) . "\n";
    }

    /**
     * The paths the generated robots.txt disallows for the control panel.
     *
     * Two things worth being exact about. These are **paths**, not URLs: `Disallow` takes a path
     * and a crawler handed `https://example.com/admin` matches it against the path literally and
     * therefore never at all — so the line that was supposed to hide the control panel published it
     * without hiding anything.
     *
     * And whether the control panel is named here at all is a decision, not a default. On the usual
     * `admin` trigger the line is conventional and costs nothing, because everybody already knows
     * where a Craft control panel is. On a *customised* trigger it is the opposite: the trigger was
     * customised to keep the control panel out of sight, and robots.txt is the most reliably fetched
     * file on the site. Disallowing it was never protection — the control panel needs a login, and a
     * crawler that ignores robots.txt is the one you were worried about — so `auto` keeps the
     * convention where it is free and drops it where it costs something.
     *
     * @return list<string>
     */
    public function cpDisallows(): array
    {
        $settings = Plugin::getInstance()->getSettings();

        if ($settings->robotsDisallowCp === Settings::CP_NEVER) {
            return [];
        }

        $general = Craft::$app->getConfig()->getGeneral();
        $trigger = trim((string)$general->cpTrigger, '/');

        // A headless install serves the control panel from its own domain and has no trigger to
        // disallow; there is nothing on this host to name.
        $paths = $trigger === ''
            ? []
            : ['/' . $trigger];

        if ($settings->robotsDisallowCp === Settings::CP_AUTO && $trigger !== self::DEFAULT_CP_TRIGGER) {
            $paths = [];
        }

        // The resource path leaks nothing — it is public, cacheable and the same on nearly every
        // install — so it stays whenever the operator has not switched the section off entirely.
        // It comes from `resourceBaseUrl` rather than `resourceBasePath`, which is a directory on
        // disk and not something a crawler could ask for.
        $resources = parse_url(Craft::getAlias((string)$general->resourceBaseUrl) ?: '', PHP_URL_PATH);
        $paths[] = '/' . trim(is_string($resources) && $resources !== '' ? $resources : 'cpresources', '/') . '/';

        return $paths;
    }

    /**
     * A static robots.txt in the web root, if there is one.
     *
     * It wins over anything Craft routes, so serving a generated one while this file exists would
     * be a setting that appears to work and does nothing. The settings screen says so.
     */
    public function staticRobotsPath(): ?string
    {
        $path = Craft::getAlias('@webroot');

        if (!is_string($path)) {
            return null;
        }

        $file = $path . DIRECTORY_SEPARATOR . 'robots.txt';

        return is_file($file) ? $file : null;
    }

    // -------------------------------------------------------------------- log

    /**
     * Which known agent a user agent string belongs to, or null.
     *
     * One precompiled alternation over every signature, so the cost on a miss — which is every
     * human request — is a single regex that fails fast.
     */
    public function detect(string $userAgent): ?CrawlerAgent
    {
        if ($userAgent === '') {
            return null;
        }

        if (!preg_match($this->signatures(), $userAgent, $match)) {
            return null;
        }

        $needle = strtolower($match[0]);

        foreach (CrawlerAgent::all() as $agent) {
            if (in_array($needle, $agent->signatures, true)) {
                return $agent;
            }
        }

        return null;
    }

    /**
     * Record a hit. Never throws: a logging failure must not take down the page being logged.
     */
    public function record(CrawlerAgent $agent, string $url, ?int $statusCode, string $userAgent, ?string $ip, ?int $siteId): void
    {
        try {
            $row = new CrawlRecord();
            $row->agent = $agent->token;
            $row->userAgent = mb_substr($userAgent, 0, 512);
            $row->url = $url;
            $row->urlHash = Plugin::getInstance()->urls->hash($url);
            $row->statusCode = $statusCode;
            $row->ip = $ip !== null ? mb_substr($ip, 0, 45) : null;
            $row->siteId = $siteId;
            $row->verified = null;
            $row->save(false);
        } catch (\Throwable $e) {
            Craft::warning("Sanka could not record a crawler hit: {$e->getMessage()}", Plugin::LOG_CATEGORY);
        }
    }

    /**
     * Hits per agent over a window, busiest first.
     *
     * @return list<array{agent: string, label: string, vendor: string, purpose: string, hits: int, verified: int, spoofed: int, lastSeen: string|null}>
     */
    public function summary(int $days = 30): array
    {
        $cutoff = Db::prepareDateForDb((new DateTime())->modify("-{$days} days"));

        $rows = (new Query())
            ->select([
                'agent',
                'hits' => 'COUNT(*)',
                'verified' => 'SUM(CASE WHEN [[verified]] = 1 THEN 1 ELSE 0 END)',
                'spoofed' => 'SUM(CASE WHEN [[verified]] = 0 THEN 1 ELSE 0 END)',
                'lastSeen' => 'MAX([[dateCreated]])',
            ])
            ->from(CrawlRecord::TABLE)
            ->where(['>=', 'dateCreated', $cutoff])
            ->groupBy(['agent'])
            ->orderBy(['hits' => SORT_DESC])
            ->all();

        return array_map(static function(array $row): array {
            $agent = CrawlerAgent::find((string)$row['agent']);

            return [
                'agent' => (string)$row['agent'],
                'label' => $agent?->label ?? (string)$row['agent'],
                'vendor' => $agent?->vendor ?? '',
                'purpose' => $agent?->purpose ?? '',
                'hits' => (int)$row['hits'],
                'verified' => (int)$row['verified'],
                'spoofed' => (int)$row['spoofed'],
                'lastSeen' => $row['lastSeen'] !== null ? (string)$row['lastSeen'] : null,
            ];
        }, $rows);
    }

    /**
     * The pages AI agents read most.
     *
     * @return list<array{url: string, hits: int, agents: int}>
     */
    public function topPages(int $days = 30, int $limit = 25): array
    {
        $cutoff = Db::prepareDateForDb((new DateTime())->modify("-{$days} days"));

        $rows = (new Query())
            ->select(['url' => 'MIN([[url]])', 'hits' => 'COUNT(*)', 'agents' => 'COUNT(DISTINCT [[agent]])'])
            ->from(CrawlRecord::TABLE)
            ->where(['>=', 'dateCreated', $cutoff])
            ->groupBy(['urlHash'])
            ->orderBy(['hits' => SORT_DESC])
            ->limit($limit)
            ->all();

        return array_map(static fn(array $row): array => [
            'url' => (string)$row['url'],
            'hits' => (int)$row['hits'],
            'agents' => (int)$row['agents'],
        ], $rows);
    }

    /**
     * @return list<CrawlRecord>
     */
    public function recent(int $limit = 100, ?string $agent = null): array
    {
        $query = CrawlRecord::find()->orderBy(['dateCreated' => SORT_DESC])->limit($limit);

        if ($agent !== null) {
            $query->where(['agent' => $agent]);
        }

        /** @var list<CrawlRecord> */
        return $query->all();
    }

    // ----------------------------------------------------------- verification

    /**
     * Forward-confirmed reverse DNS on unverified rows.
     *
     * Reverse the IP, check the hostname belongs to the vendor, then resolve that hostname forward
     * and check it comes back to the same IP. Only the third step makes it proof: a reverse record
     * alone is controlled by whoever owns the IP block.
     *
     * Results are memoised per IP within a run, because a crawler visiting 400 pages is 400 rows and
     * one address.
     *
     * @return array{checked: int, verified: int, spoofed: int, unknown: int}
     */
    public function verifyPending(int $limit = 200): array
    {
        /** @var list<CrawlRecord> $rows */
        $rows = CrawlRecord::find()
            ->where(['verified' => null])
            ->andWhere(['not', ['ip' => null]])
            ->orderBy(['dateCreated' => SORT_DESC])
            ->limit($limit)
            ->all();

        $counts = ['checked' => 0, 'verified' => 0, 'spoofed' => 0, 'unknown' => 0];
        $seen = [];

        foreach ($rows as $row) {
            $agent = CrawlerAgent::find((string)$row->agent);

            if ($agent === null) {
                $counts['unknown']++;

                continue;
            }

            $key = $row->agent . '|' . $row->ip;
            $verdict = $seen[$key] ??= $this->verify((string)$row->ip, $agent);

            $counts['checked']++;

            if ($verdict === null) {
                $counts['unknown']++;

                continue;
            }

            $row->verified = $verdict;
            $row->save(false);

            $counts[$verdict ? 'verified' : 'spoofed']++;
        }

        return $counts;
    }

    /**
     * True if the IP really is this agent, false if it is pretending, null if there is no way to
     * tell — the vendor publishes no reverse records Sanka knows about.
     */
    public function verify(string $ip, CrawlerAgent $agent): ?bool
    {
        $domains = self::VENDOR_DOMAINS[$agent->vendor] ?? null;

        if ($domains === null) {
            return null;
        }

        $hostname = @gethostbyaddr($ip);

        if (!is_string($hostname) || $hostname === '' || $hostname === $ip) {
            // No reverse record at all. Every vendor in the map above publishes them, so this is
            // evidence of forgery rather than an absence of evidence.
            return false;
        }

        $hostname = rtrim(strtolower($hostname), '.');
        $matches = false;

        foreach ($domains as $domain) {
            if ($hostname === $domain || str_ends_with($hostname, '.' . $domain)) {
                $matches = true;

                break;
            }
        }

        if (!$matches) {
            return false;
        }

        $forward = @gethostbynamel($hostname);

        return is_array($forward) && in_array($ip, $forward, true);
    }

    // ------------------------------------------------------------ maintenance

    public function prune(int $days): int
    {
        $cutoff = Db::prepareDateForDb((new DateTime())->modify("-{$days} days"));

        return Craft::$app->getDb()->createCommand()
            ->delete(CrawlRecord::TABLE, ['<', 'dateCreated', $cutoff])
            ->execute();
    }

    // ----------------------------------------------------------------- private

    private function signatures(): string
    {
        if ($this->signatureRegex !== null) {
            return $this->signatureRegex;
        }

        $tokens = [];

        foreach (CrawlerAgent::all() as $agent) {
            foreach ($agent->signatures as $signature) {
                $tokens[$signature] = preg_quote($signature, '/');
            }
        }

        // Longest first, so `claude-searchbot` is not swallowed by a shorter overlapping token.
        $patterns = array_values($tokens);
        usort($patterns, static fn(string $a, string $b): int => strlen($b) <=> strlen($a));

        return $this->signatureRegex = '/' . implode('|', $patterns) . '/i';
    }
}
